export const FILTER_TEMPERAMENT = 'FILTER_TEMPERAMENT';
export const FILTER_ORIGIN = 'FILTER_ORIGIN';
export const SORT_ALPHABETICAL = 'SORT_ALPHABETICAL'
export const SORT_WEIGHT = 'SORT_WEIGHT'
export const SET_DOGS = 'SET_DOGS'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'